spring:
  application:
    name: petcontrol

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/petcontrol}
    username: ${DB_USERNAME:user}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migrations
    
  web:
    cors:
      allowed-origins: ${WEB_API:http://localhost:3000}

management:
  endpoints:
    web:
      cors:
        allowed-origins: ${WEB_API:http://localhost:3000}
        allowed-methods: OPTIONS, GET, POST